[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# Allow manual customizations to release.yml
allow-dirty = ["ci"]
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Whether to install an updater program
install-updater = true
# A GitHub repo to push Homebrew formulas to
tap = "Cooklang/homebrew-tap"
# Path that installers should place binaries in
install-path = "CARGO_HOME"

# Use native ARM64 runners for ARM64 Linux builds (free in public repos)
[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "ubuntu-22.04-arm"
