[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Whether to auto-publish releases to package managers
publish-jobs = ["homebrew"]
# Generate installer update receipts for axoupdater
install-updater = true
# Homebrew tap to publish to
tap = "Cooklang/homebrew-tap"

# System dependencies for Linux builds
[dist.dependencies.apt]
libglib2.0-dev = "*"
libgtk-3-dev = "*"
libappindicator3-dev = "*"
libxdo-dev = "*"
